-- ============================================================
-- CYBERSAAS
-- INITIAL DATABASE SCHEMA
--
-- Migration:
-- 000001_initial_schema.up.sql
--
-- PostgreSQL
--
-- IMPORTANT:
-- IDs are intentionally NOT generated by PostgreSQL.
-- The application/client must provide UUIDs explicitly.
-- ============================================================


-- ============================================================
-- ENUM TYPES
-- ============================================================

CREATE TYPE user_role AS ENUM (
    'platform_admin',
    'owner',
    'attendant'
);

CREATE TYPE user_status AS ENUM (
    'active',
    'inactive',
    'suspended'
);

CREATE TYPE branch_status AS ENUM (
    'active',
    'inactive'
);

CREATE TYPE terminal_status AS ENUM (
    'pending',
    'active',
    'disabled'
);

CREATE TYPE customer_type AS ENUM (
    'adult',
    'child'
);

CREATE TYPE session_type AS ENUM (
    'pay_after',
    'prepaid'
);

CREATE TYPE session_status AS ENUM (
    'active',
    'completed',
    'expired',
    'cancelled'
);

CREATE TYPE sale_status AS ENUM (
    'completed',
    'voided',
    'refunded'
);

CREATE TYPE payment_method AS ENUM (
    'cash',
    'mpesa',
    'other'
);

CREATE TYPE payment_status AS ENUM (
    'pending',
    'confirmed',
    'failed',
    'cancelled',
    'refunded'
);

CREATE TYPE discount_type AS ENUM (
    'fixed',
    'percentage'
);

CREATE TYPE sync_status AS ENUM (
    'pending',
    'processing',
    'synced',
    'failed'
);


-- ============================================================
-- TENANTS
-- One tenant = one cybercafe business/owner account.
-- ============================================================

CREATE TABLE tenants (
    id UUID PRIMARY KEY,

    business_name VARCHAR(200) NOT NULL,

    owner_name VARCHAR(200) NOT NULL,

    phone VARCHAR(30) NOT NULL,

    email VARCHAR(255),

    status VARCHAR(30) NOT NULL DEFAULT 'active',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tenants_status
    ON tenants(status);


-- ============================================================
-- USERS
--
-- IMPORTANT:
-- There is NO branch_id here.
--
-- Owner:
--     tenant_id -> tenant
--
-- Attendant:
--     tenant_id -> tenant
--     branch access -> attendant_branch_assignments
-- ============================================================

CREATE TABLE users (
    id UUID PRIMARY KEY,

    tenant_id UUID
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    full_name VARCHAR(200) NOT NULL,

    email VARCHAR(255),

    phone VARCHAR(30),

    password_hash TEXT NOT NULL,

    role user_role NOT NULL,

    status user_status NOT NULL DEFAULT 'active',

    last_login_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uq_users_email
    ON users(LOWER(email))
    WHERE email IS NOT NULL;

CREATE INDEX idx_users_tenant
    ON users(tenant_id);

CREATE INDEX idx_users_role
    ON users(role);

CREATE INDEX idx_users_status
    ON users(status);


-- ============================================================
-- BRANCHES
-- ============================================================

CREATE TABLE branches (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    name VARCHAR(200) NOT NULL,

    address TEXT,

    phone VARCHAR(30),

    status branch_status NOT NULL DEFAULT 'active',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (tenant_id, name)
);

CREATE INDEX idx_branches_tenant
    ON branches(tenant_id);

CREATE INDEX idx_branches_status
    ON branches(status);


-- ============================================================


CREATE TABLE attendant_branch_assignments (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    assigned_by UUID
        REFERENCES users(id)
        ON DELETE RESTRICT,

    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    unassigned_at TIMESTAMPTZ
);

CREATE INDEX idx_attendant_assignments_user
    ON attendant_branch_assignments(user_id);

CREATE INDEX idx_attendant_assignments_branch
    ON attendant_branch_assignments(branch_id);

CREATE INDEX idx_attendant_assignments_tenant
    ON attendant_branch_assignments(tenant_id);

CREATE UNIQUE INDEX uq_attendant_one_active_branch
    ON attendant_branch_assignments(user_id)
    WHERE unassigned_at IS NULL;


-- ============================================================
-- LICENCE KEYS
--
-- Used for initial terminal enrollment.
--
-- IMPORTANT:
-- The licence key is NOT the permanent terminal credential.
-- ============================================================

CREATE TABLE licence_keys (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    licence_key_hash TEXT NOT NULL UNIQUE,

    created_by UUID
        REFERENCES users(id)
        ON DELETE RESTRICT,

    expires_at TIMESTAMPTZ,

    used_at TIMESTAMPTZ,

    revoked_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_licence_keys_tenant
    ON licence_keys(tenant_id);

CREATE INDEX idx_licence_keys_branch
    ON licence_keys(branch_id);


-- ============================================================
-- TERMINALS / PCS
-- ============================================================

CREATE TABLE terminals (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    terminal_code VARCHAR(100) NOT NULL,

    machine_name VARCHAR(200),

    device_identifier VARCHAR(255),

    status terminal_status NOT NULL DEFAULT 'pending',

    registered_at TIMESTAMPTZ,

    last_seen_at TIMESTAMPTZ,

    disabled_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (branch_id, terminal_code),

    UNIQUE (device_identifier)
);

CREATE INDEX idx_terminals_tenant
    ON terminals(tenant_id);

CREATE INDEX idx_terminals_branch
    ON terminals(branch_id);

CREATE INDEX idx_terminals_status
    ON terminals(status);


-- ============================================================
-- TERMINAL CREDENTIALS
-- ============================================================

CREATE TABLE terminal_credentials (
    id UUID PRIMARY KEY,

    terminal_id UUID NOT NULL
        REFERENCES terminals(id)
        ON DELETE RESTRICT,

    credential_hash TEXT NOT NULL UNIQUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    revoked_at TIMESTAMPTZ
);

CREATE INDEX idx_terminal_credentials_terminal
    ON terminal_credentials(terminal_id);


-- ============================================================
-- CUSTOMERS
--
-- Adult:
--     full name
--     phone
--     ID
--
-- Child:
--     child name
--     parent phone
--     parent ID
--
-- IDs are encrypted for storage and hashed for lookup.
--
-- NO browsing history is stored.
-- ============================================================

CREATE TABLE customers (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    customer_type customer_type NOT NULL,

    full_name VARCHAR(200) NOT NULL,

    phone VARCHAR(30),

    id_number_encrypted TEXT,

    id_number_hash TEXT,

    parent_name VARCHAR(200),

    parent_phone VARCHAR(30),

    parent_id_number_encrypted TEXT,

    parent_id_number_hash TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_customers_tenant
    ON customers(tenant_id);

CREATE INDEX idx_customers_branch
    ON customers(branch_id);

CREATE INDEX idx_customers_id_hash
    ON customers(id_number_hash);

CREATE INDEX idx_customers_parent_id_hash
    ON customers(parent_id_number_hash);


-- ============================================================
-- BILLING CONFIGURATION
-- ============================================================

CREATE TABLE billing_configs (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    rate_per_minute NUMERIC(12,2) NOT NULL DEFAULT 1.00,

    minimum_charge NUMERIC(12,2) NOT NULL DEFAULT 10.00,

    billing_interval_minutes INTEGER NOT NULL DEFAULT 1,

    rounding_mode VARCHAR(30) NOT NULL DEFAULT 'up',

    currency VARCHAR(10) NOT NULL DEFAULT 'KES',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(branch_id)
);

ALTER TABLE billing_configs
ADD CONSTRAINT chk_billing_rate_positive
CHECK (rate_per_minute >= 0);

ALTER TABLE billing_configs
ADD CONSTRAINT chk_billing_minimum_positive
CHECK (minimum_charge >= 0);

ALTER TABLE billing_configs
ADD CONSTRAINT chk_billing_interval_positive
CHECK (billing_interval_minutes > 0);


-- ============================================================
-- SERVICES
--
-- Owner creates services.
--
-- Examples:
-- Printing
-- Photocopy
-- Scanning
-- Typing
-- Binding
--
-- Nothing is hard-coded.
-- ============================================================

CREATE TABLE services (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    name VARCHAR(200) NOT NULL,

    description TEXT,

    price NUMERIC(12,2) NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(branch_id, name)
);

CREATE INDEX idx_services_tenant
    ON services(tenant_id);

CREATE INDEX idx_services_branch
    ON services(branch_id);

CREATE INDEX idx_services_active
    ON services(branch_id, active);

ALTER TABLE services
ADD CONSTRAINT chk_service_price_positive
CHECK (price >= 0);


-- ============================================================
-- SESSIONS
--
-- IMPORTANT:
-- This table is RANGE PARTITIONED by started_at.
--
-- Because PostgreSQL requires the partition key to be included
-- in a primary/unique constraint, the primary key is:
--
--     (id, started_at)
--
-- The client still generates the UUID `id`.
--
-- No browsing history or URLs are stored.
-- ============================================================

CREATE TABLE sessions (
    id UUID NOT NULL,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    terminal_id UUID NOT NULL
        REFERENCES terminals(id)
        ON DELETE RESTRICT,

    customer_id UUID NOT NULL
        REFERENCES customers(id)
        ON DELETE RESTRICT,

    attendant_id UUID
        REFERENCES users(id)
        ON DELETE RESTRICT,

    session_type session_type NOT NULL,

    status session_status NOT NULL DEFAULT 'active',

    started_at TIMESTAMPTZ NOT NULL,

    ended_at TIMESTAMPTZ,

    prepaid_amount NUMERIC(12,2),

    allowed_minutes INTEGER,

    rate_per_minute NUMERIC(12,2),

    minimum_charge NUMERIC(12,2),

    final_amount NUMERIC(12,2),

    client_operation_id UUID NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (id, started_at),

    UNIQUE (client_operation_id, started_at),

    CHECK (
        ended_at IS NULL
        OR ended_at >= started_at
    ),

    CHECK (
        prepaid_amount IS NULL
        OR prepaid_amount >= 0
    ),

    CHECK (
        allowed_minutes IS NULL
        OR allowed_minutes >= 0
    ),

    CHECK (
        rate_per_minute IS NULL
        OR rate_per_minute >= 0
    ),

    CHECK (
        minimum_charge IS NULL
        OR minimum_charge >= 0
    ),

    CHECK (
        final_amount IS NULL
        OR final_amount >= 0
    )
)
PARTITION BY RANGE (started_at);


-- ============================================================
-- SESSION PARTITIONS
--
-- We create several years ahead plus a DEFAULT partition.
--
-- The default partition prevents a future session from failing
-- simply because a new yearly partition has not yet been added.
--
-- The backend should create future yearly partitions as part of
-- database maintenance.
-- ============================================================

CREATE TABLE sessions_2025
PARTITION OF sessions
FOR VALUES FROM ('2025-01-01 00:00:00+00')
             TO ('2026-01-01 00:00:00+00');

CREATE TABLE sessions_2026
PARTITION OF sessions
FOR VALUES FROM ('2026-01-01 00:00:00+00')
             TO ('2027-01-01 00:00:00+00');

CREATE TABLE sessions_2027
PARTITION OF sessions
FOR VALUES FROM ('2027-01-01 00:00:00+00')
             TO ('2028-01-01 00:00:00+00');

CREATE TABLE sessions_2028
PARTITION OF sessions
FOR VALUES FROM ('2028-01-01 00:00:00+00')
             TO ('2029-01-01 00:00:00+00');

CREATE TABLE sessions_2029
PARTITION OF sessions
FOR VALUES FROM ('2029-01-01 00:00:00+00')
             TO ('2030-01-01 00:00:00+00');

CREATE TABLE sessions_2030
PARTITION OF sessions
FOR VALUES FROM ('2030-01-01 00:00:00+00')
             TO ('2031-01-01 00:00:00+00');

CREATE TABLE sessions_2031
PARTITION OF sessions
FOR VALUES FROM ('2031-01-01 00:00:00+00')
             TO ('2032-01-01 00:00:00+00');

CREATE TABLE sessions_default
PARTITION OF sessions DEFAULT;


CREATE INDEX idx_sessions_tenant
    ON sessions(tenant_id);

CREATE INDEX idx_sessions_branch
    ON sessions(branch_id);

CREATE INDEX idx_sessions_terminal
    ON sessions(terminal_id);

CREATE INDEX idx_sessions_customer
    ON sessions(customer_id);

CREATE INDEX idx_sessions_attendant
    ON sessions(attendant_id);

CREATE INDEX idx_sessions_status
    ON sessions(status);

CREATE INDEX idx_sessions_started
    ON sessions(started_at);


-- ============================================================
-- SALES / TRANSACTIONS
-- ============================================================

CREATE TABLE sales (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    customer_id UUID
        REFERENCES customers(id)
        ON DELETE RESTRICT,

    session_id UUID,

    session_started_at TIMESTAMPTZ,

    terminal_id UUID
        REFERENCES terminals(id)
        ON DELETE RESTRICT,

    attendant_id UUID
        REFERENCES users(id)
        ON DELETE RESTRICT,

    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,

    discount_type discount_type,

    discount_value NUMERIC(12,2) NOT NULL DEFAULT 0,

    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,

    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,

    status sale_status NOT NULL DEFAULT 'completed',

    void_reason TEXT,

    voided_by UUID
        REFERENCES users(id)
        ON DELETE RESTRICT,

    voided_at TIMESTAMPTZ,

    client_operation_id UUID NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(client_operation_id),

    CHECK (subtotal >= 0),

    CHECK (discount_value >= 0),

    CHECK (discount_amount >= 0),

    CHECK (total_amount >= 0)
);

-- A sale referring to a session must reference both
-- session UUID and the partition key.
ALTER TABLE sales
ADD CONSTRAINT fk_sales_session
FOREIGN KEY (session_id, session_started_at)
REFERENCES sessions(id, started_at)
ON DELETE RESTRICT;

CREATE INDEX idx_sales_tenant
    ON sales(tenant_id);

CREATE INDEX idx_sales_branch
    ON sales(branch_id);

CREATE INDEX idx_sales_customer
    ON sales(customer_id);

CREATE INDEX idx_sales_session
    ON sales(session_id, session_started_at);

CREATE INDEX idx_sales_terminal
    ON sales(terminal_id);

CREATE INDEX idx_sales_attendant
    ON sales(attendant_id);

CREATE INDEX idx_sales_created
    ON sales(created_at);

CREATE INDEX idx_sales_status
    ON sales(status);


-- ============================================================
-- SALE ITEMS
-- ============================================================

CREATE TABLE sale_items (
    id UUID PRIMARY KEY,

    sale_id UUID NOT NULL
        REFERENCES sales(id)
        ON DELETE RESTRICT,

    service_id UUID
        REFERENCES services(id)
        ON DELETE RESTRICT,

    description VARCHAR(255) NOT NULL,

    quantity NUMERIC(12,2) NOT NULL DEFAULT 1,

    unit_price NUMERIC(12,2) NOT NULL,

    line_total NUMERIC(12,2) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CHECK (quantity > 0),

    CHECK (unit_price >= 0),

    CHECK (line_total >= 0)
);

CREATE INDEX idx_sale_items_sale
    ON sale_items(sale_id);

CREATE INDEX idx_sale_items_service
    ON sale_items(service_id);


-- ============================================================
-- PAYMENTS
-- ============================================================

CREATE TABLE payments (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    sale_id UUID NOT NULL
        REFERENCES sales(id)
        ON DELETE RESTRICT,

    method payment_method NOT NULL,

    status payment_status NOT NULL DEFAULT 'pending',

    amount NUMERIC(12,2) NOT NULL,

    phone VARCHAR(30),

    external_reference VARCHAR(255),

    mpesa_receipt_number VARCHAR(255),

    provider_request_id VARCHAR(255),

    provider_transaction_id VARCHAR(255),

    failure_reason TEXT,

    confirmed_at TIMESTAMPTZ,

    client_operation_id UUID,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CHECK (amount >= 0)
);

CREATE UNIQUE INDEX uq_payment_client_operation
    ON payments(client_operation_id)
    WHERE client_operation_id IS NOT NULL;

CREATE UNIQUE INDEX uq_payment_external_reference
    ON payments(external_reference)
    WHERE external_reference IS NOT NULL;

CREATE UNIQUE INDEX uq_payment_provider_transaction
    ON payments(provider_transaction_id)
    WHERE provider_transaction_id IS NOT NULL;

CREATE INDEX idx_payments_tenant
    ON payments(tenant_id);

CREATE INDEX idx_payments_branch
    ON payments(branch_id);

CREATE INDEX idx_payments_sale
    ON payments(sale_id);

CREATE INDEX idx_payments_status
    ON payments(status);


-- ============================================================
-- PAYMENT CALLBACKS
--
-- Protects against duplicate M-Pesa/provider callbacks.
-- ============================================================

CREATE TABLE payment_callbacks (
    id UUID PRIMARY KEY,

    provider VARCHAR(50) NOT NULL,

    callback_reference VARCHAR(255),

    provider_transaction_id VARCHAR(255),

    payload JSONB NOT NULL,

    processed BOOLEAN NOT NULL DEFAULT FALSE,

    processed_at TIMESTAMPTZ,

    processing_error TEXT,

    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uq_payment_callback_reference
    ON payment_callbacks(provider, callback_reference)
    WHERE callback_reference IS NOT NULL;

CREATE UNIQUE INDEX uq_payment_callback_transaction
    ON payment_callbacks(provider, provider_transaction_id)
    WHERE provider_transaction_id IS NOT NULL;

CREATE INDEX idx_payment_callbacks_transaction
    ON payment_callbacks(provider_transaction_id);


-- ============================================================
-- RECEIPTS
--
-- One completed sale -> one primary receipt.
-- Reprints are recorded separately.
-- ============================================================

CREATE TABLE receipts (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    sale_id UUID NOT NULL
        REFERENCES sales(id)
        ON DELETE RESTRICT,

    payment_id UUID
        REFERENCES payments(id)
        ON DELETE RESTRICT,

    receipt_number VARCHAR(100) NOT NULL,

    receipt_type VARCHAR(50) NOT NULL DEFAULT 'sale',

    issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    printed_at TIMESTAMPTZ,

    reprint_count INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(branch_id, receipt_number),

    UNIQUE(sale_id)
);

CREATE INDEX idx_receipts_tenant
    ON receipts(tenant_id);

CREATE INDEX idx_receipts_branch
    ON receipts(branch_id);

CREATE INDEX idx_receipts_sale
    ON receipts(sale_id);

CREATE INDEX idx_receipts_issued
    ON receipts(issued_at);


-- ============================================================
-- RECEIPT REPRINTS
-- ============================================================

CREATE TABLE receipt_reprints (
    id UUID PRIMARY KEY,

    receipt_id UUID NOT NULL
        REFERENCES receipts(id)
        ON DELETE RESTRICT,

    user_id UUID
        REFERENCES users(id)
        ON DELETE RESTRICT,

    terminal_id UUID
        REFERENCES terminals(id)
        ON DELETE RESTRICT,

    reason TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_receipt_reprints_receipt
    ON receipt_reprints(receipt_id);


-- ============================================================
-- AUDIT LOGS
--
-- Financial/compliance records are not deleted.
-- Actions are recorded here.
-- ============================================================

CREATE TABLE audit_logs (
    id UUID PRIMARY KEY,

    tenant_id UUID
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    user_id UUID
        REFERENCES users(id)
        ON DELETE RESTRICT,

    user_role user_role,

    action VARCHAR(100) NOT NULL,

    entity_type VARCHAR(100),

    entity_id UUID,

    old_value JSONB,

    new_value JSONB,

    reason TEXT,

    ip_address INET,

    device_id VARCHAR(255),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_logs_tenant
    ON audit_logs(tenant_id);

CREATE INDEX idx_audit_logs_branch
    ON audit_logs(branch_id);

CREATE INDEX idx_audit_logs_user
    ON audit_logs(user_id);

CREATE INDEX idx_audit_logs_entity
    ON audit_logs(entity_type, entity_id);

CREATE INDEX idx_audit_logs_created
    ON audit_logs(created_at);


-- ============================================================
-- OFFLINE SYNC EVENTS
--
-- Every offline operation gets a stable UUID.
--
-- The client can safely retry the same event.
-- ============================================================

CREATE TABLE sync_events (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    terminal_id UUID
        REFERENCES terminals(id)
        ON DELETE RESTRICT,

    user_id UUID
        REFERENCES users(id)
        ON DELETE RESTRICT,

    event_type VARCHAR(100) NOT NULL,

    entity_type VARCHAR(100) NOT NULL,

    entity_id UUID NOT NULL,

    payload JSONB NOT NULL,

    status sync_status NOT NULL DEFAULT 'pending',

    attempts INTEGER NOT NULL DEFAULT 0,

    last_error TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    processed_at TIMESTAMPTZ,

    UNIQUE(id)
);

CREATE INDEX idx_sync_events_tenant
    ON sync_events(tenant_id);

CREATE INDEX idx_sync_events_branch
    ON sync_events(branch_id);

CREATE INDEX idx_sync_events_terminal
    ON sync_events(terminal_id);

CREATE INDEX idx_sync_events_status
    ON sync_events(status);

CREATE INDEX idx_sync_events_entity
    ON sync_events(entity_type, entity_id);


-- ============================================================
-- IDEMPOTENCY KEYS
--
-- Prevents duplicate operations caused by retries.
--
-- Examples:
--
-- SALE_CREATED
-- PAYMENT_CREATED
-- MPESA_CALLBACK
-- RECEIPT_CREATED
-- SESSION_CREATED
-- TERMINAL_ENROLLMENT
-- ============================================================

CREATE TABLE idempotency_keys (
    id UUID PRIMARY KEY,

    tenant_id UUID
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    terminal_id UUID
        REFERENCES terminals(id)
        ON DELETE RESTRICT,

    user_id UUID
        REFERENCES users(id)
        ON DELETE RESTRICT,

    key VARCHAR(255) NOT NULL,

    operation VARCHAR(100) NOT NULL,

    request_hash VARCHAR(128),

    response_status INTEGER,

    response_body JSONB,

    resource_type VARCHAR(100),

    resource_id UUID,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    expires_at TIMESTAMPTZ,

    UNIQUE(key)
);

CREATE INDEX idx_idempotency_tenant
    ON idempotency_keys(tenant_id);

CREATE INDEX idx_idempotency_resource
    ON idempotency_keys(resource_type, resource_id);


-- ============================================================
-- TERMINAL SYNC STATE
-- ============================================================

CREATE TABLE terminal_sync_state (
    id UUID PRIMARY KEY,

    terminal_id UUID NOT NULL
        REFERENCES terminals(id)
        ON DELETE RESTRICT,

    last_pull_at TIMESTAMPTZ,

    last_push_at TIMESTAMPTZ,

    last_successful_sync_at TIMESTAMPTZ,

    last_sync_error TEXT,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(terminal_id)
);


-- ============================================================
-- BRANCH SETTINGS
-- ============================================================

CREATE TABLE branch_settings (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    setting_key VARCHAR(100) NOT NULL,

    setting_value JSONB NOT NULL,

    updated_by UUID
        REFERENCES users(id)
        ON DELETE RESTRICT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(branch_id, setting_key)
);


-- ============================================================
-- DAILY REPORT SNAPSHOTS
-- ============================================================

CREATE TABLE daily_reports (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    report_date DATE NOT NULL,

    total_customers INTEGER NOT NULL DEFAULT 0,

    adult_customers INTEGER NOT NULL DEFAULT 0,

    child_customers INTEGER NOT NULL DEFAULT 0,

    total_sessions INTEGER NOT NULL DEFAULT 0,

    total_browsing_minutes INTEGER NOT NULL DEFAULT 0,

    browsing_revenue NUMERIC(12,2) NOT NULL DEFAULT 0,

    service_revenue NUMERIC(12,2) NOT NULL DEFAULT 0,

    total_sales NUMERIC(12,2) NOT NULL DEFAULT 0,

    total_discounts NUMERIC(12,2) NOT NULL DEFAULT 0,

    cash_total NUMERIC(12,2) NOT NULL DEFAULT 0,

    mpesa_total NUMERIC(12,2) NOT NULL DEFAULT 0,

    other_payment_total NUMERIC(12,2) NOT NULL DEFAULT 0,

    voided_total NUMERIC(12,2) NOT NULL DEFAULT 0,

    refunded_total NUMERIC(12,2) NOT NULL DEFAULT 0,

    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(branch_id, report_date)
);

CREATE INDEX idx_daily_reports_tenant
    ON daily_reports(tenant_id);

CREATE INDEX idx_daily_reports_branch_date
    ON daily_reports(branch_id, report_date);


-- ============================================================
-- MONTHLY REPORT SNAPSHOTS
-- ============================================================

CREATE TABLE monthly_reports (
    id UUID PRIMARY KEY,

    tenant_id UUID NOT NULL
        REFERENCES tenants(id)
        ON DELETE RESTRICT,

    branch_id UUID NOT NULL
        REFERENCES branches(id)
        ON DELETE RESTRICT,

    report_year INTEGER NOT NULL,

    report_month INTEGER NOT NULL,

    total_customers INTEGER NOT NULL DEFAULT 0,

    total_sessions INTEGER NOT NULL DEFAULT 0,

    total_browsing_minutes INTEGER NOT NULL DEFAULT 0,

    browsing_revenue NUMERIC(12,2) NOT NULL DEFAULT 0,

    service_revenue NUMERIC(12,2) NOT NULL DEFAULT 0,

    total_sales NUMERIC(12,2) NOT NULL DEFAULT 0,

    total_discounts NUMERIC(12,2) NOT NULL DEFAULT 0,

    cash_total NUMERIC(12,2) NOT NULL DEFAULT 0,

    mpesa_total NUMERIC(12,2) NOT NULL DEFAULT 0,

    other_payment_total NUMERIC(12,2) NOT NULL DEFAULT 0,

    voided_total NUMERIC(12,2) NOT NULL DEFAULT 0,

    refunded_total NUMERIC(12,2) NOT NULL DEFAULT 0,

    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(branch_id, report_year, report_month),

    CHECK (report_month BETWEEN 1 AND 12),

    CHECK (report_year >= 2000)
);

CREATE INDEX idx_monthly_reports_tenant
    ON monthly_reports(tenant_id);

CREATE INDEX idx_monthly_reports_branch
    ON monthly_reports(branch_id);


-- ============================================================
-- UPDATED_AT FUNCTION
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- UPDATED_AT TRIGGERS
-- ============================================================

CREATE TRIGGER trg_tenants_updated_at
BEFORE UPDATE ON tenants
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_branches_updated_at
BEFORE UPDATE ON branches
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_terminals_updated_at
BEFORE UPDATE ON terminals
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_customers_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_billing_configs_updated_at
BEFORE UPDATE ON billing_configs
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_services_updated_at
BEFORE UPDATE ON services
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_sessions_updated_at
BEFORE UPDATE ON sessions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_payments_updated_at
BEFORE UPDATE ON payments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_terminal_sync_state_updated_at
BEFORE UPDATE ON terminal_sync_state
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_branch_settings_updated_at
BEFORE UPDATE ON branch_settings
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();



-- Optional: Scoped idempotency key
ALTER TABLE idempotency_keys DROP CONSTRAINT idempotency_keys_key_key;
CREATE UNIQUE INDEX uq_idempotency_tenant_key ON idempotency_keys (tenant_id, key);


-- ============================================================
-- END OF INITIAL SCHEMA
-- ============================================================