package terminal

import "time"

// Terminal represents a registered cyber café PC.
type Terminal struct {
	ID           string     `json:"id"`
	TenantID     string     `json:"tenant_id"`
	BranchID     string     `json:"branch_id"`
	BranchName   *string    `json:"branch_name,omitempty"`
	TerminalCode string     `json:"terminal_code"`
	MachineName  *string    `json:"machine_name,omitempty"`
	DeviceID     *string    `json:"device_identifier,omitempty"`
	Status       string     `json:"status"`
	RegisteredAt *time.Time `json:"registered_at,omitempty"`
	LastSeenAt   *time.Time `json:"last_seen_at,omitempty"`
	DisabledAt   *time.Time `json:"disabled_at,omitempty"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

// LicenceKey represents a temporary key generated by the Cyber Owner.
//
// The plaintext key is never stored in the database.
// Only its SHA-256 hash is stored.
type LicenceKey struct {
	ID         string     `json:"id"`
	TenantID   string     `json:"tenant_id"`
	BranchID   string     `json:"branch_id"`
	BranchName *string    `json:"branch_name,omitempty"`
	ExpiresAt  *time.Time `json:"expires_at,omitempty"`
	UsedAt     *time.Time `json:"used_at,omitempty"`
	RevokedAt  *time.Time `json:"revoked_at,omitempty"`
	CreatedBy  *string    `json:"created_by,omitempty"`
	CreatedAt  time.Time  `json:"created_at"`
}

// GenerateLicenceKeyRequest controls how long the temporary key should live.
type GenerateLicenceKeyRequest struct {
	BranchID       string `json:"branch_id" binding:"required"`
	ExpiresInHours *int   `json:"expires_in_hours,omitempty"`
}

// GenerateLicenceKeyResponse contains the plaintext licence key.
//
// This plaintext value is shown only when the key is generated.
type GenerateLicenceKeyResponse struct {
	ID         string    `json:"id"`
	BranchID   string    `json:"branch_id"`
	BranchName *string   `json:"branch_name,omitempty"`
	LicenceKey string    `json:"licence_key"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
}

// RegisterTerminalRequest is sent by the C# PC client.
//
// IMPORTANT:
// There is no owner JWT here.
// The licence key itself is the temporary authorization
// that allows the PC to register.
type RegisterTerminalRequest struct {
	LicenceKey  string `json:"licence_key" binding:"required"`
	MachineName string `json:"machine_name" binding:"required"`
	DeviceID    string `json:"device_identifier" binding:"required"`
}

// RegisterTerminalResponse is returned to the PC once.
//
// The credential is the permanent terminal credential.
// The C# client must store it securely.
type RegisterTerminalResponse struct {
	TerminalID   string `json:"terminal_id"`
	TenantID     string `json:"tenant_id"`
	BranchID     string `json:"branch_id"`
	TerminalCode string `json:"terminal_code"`
	Credential   string `json:"credential"`
}

// RenameTerminalRequest changes only the display machine name.
type RenameTerminalRequest struct {
	MachineName string `json:"machine_name" binding:"required"`
}

// ChangeStatusRequest changes terminal status.
type ChangeStatusRequest struct {
	Status string `json:"status" binding:"required"`
}

// MoveTerminalRequest moves a terminal to another branch.
type MoveTerminalRequest struct {
	BranchID string `json:"branch_id" binding:"required"`
}

// TerminalListResponse contains paginated terminals.
type TerminalListResponse struct {
	Terminals []Terminal `json:"terminals"`
	Total     int64      `json:"total"`
}

// LicenceKeyListResponse contains paginated licence keys.
type LicenceKeyListResponse struct {
	LicenceKeys []LicenceKey `json:"licence_keys"`
	Total       int64        `json:"total"`
}

type TerminalAuthRequest struct {
	Credential string `json:"credential" binding:"required"`
}

type TerminalAuthResponse struct {
	TerminalID string `json:"terminal_id"`
	TenantID   string `json:"tenant_id"`
	BranchID   string `json:"branch_id"`
}

type TerminalHeartbeatRequest struct {
	MachineName      *string `json:"machine_name"`
	DeviceIdentifier *string `json:"device_identifier"`
}

type TerminalHeartbeatResponse struct {
	TerminalID     string    `json:"terminal_id"`
	ServerTime     time.Time `json:"server_time"`
	DesiredState   string    `json:"desired_state"`
	CommandVersion int64     `json:"command_version"`
}

type TerminalControlState struct {
	TerminalID     string    `json:"terminal_id"`
	DesiredState   string    `json:"desired_state"`
	CommandVersion int64     `json:"command_version"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ChangeTerminalLockStateRequest struct {
	State string `json:"state" binding:"required"`
}

type TerminalCommand string

const (
	CommandRestart  TerminalCommand = "restart"
	CommandShutdown TerminalCommand = "shutdown"
)

type TerminalCommandResponse struct {
	ID             string          `json:"id"`
	TerminalID     string          `json:"terminal_id"`
	Command        TerminalCommand `json:"command"`
	Status         string          `json:"status"`
	CommandVersion int64           `json:"command_version"`
	CreatedAt      time.Time       `json:"created_at"`
	ExecutedAt     *time.Time      `json:"executed_at,omitempty"`
	AcknowledgedAt *time.Time      `json:"acknowledged_at,omitempty"`
	ErrorMessage   *string         `json:"error_message,omitempty"`
}
